### ISSUE TITLE
"@allcontributors[bot]" does not trigger a pull request

### ISSUE THREAD

**Issue by gr2m** [all-contributors/all-contributors-bot#150]
**Describe the bug**

When I start typing `@all`, the `@allcontributors[bot]` gets suggested

![image](https://user-images.githubusercontent.com/39992/53197862-f7003880-35cf-11e9-8313-aa01f1b41e39.png)

But using that instead of just `@allcontributors` did not seem to trigger a pull request for me. I tried it here: https://github.com/nock/nock/issues/1461 in the issue description, later removed it and added a comment, which worked

**Expected behavior**

I expected `@allcontributors[bot]` to work the same way `@allcontributors` does

**Comment by jakebolam** [comment]
@gr2m thanks for reporting this.

The bot will only read comments, not the issue description. It also only reads comments created, not edited.

Thoughts on this behaviour?

**Comment by gr2m** [comment]
Hmmm 🤔 Probably false alarm then, maybe there was a delay for the bot’s comment, I should have waited longer. I’ll try again next time and report back
