### ISSUE TITLE
Handle case where branch already exists

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/all-contributors-bot#16]
**Describe the bug**
Bot currently crashes with `We had trouble processing your request. Please try again later. When the contributor branch already exists

**To Reproduce**
1. Comment and say `@AllContributorsBot please add jakebolam for code, doc and infra`
2. Wait for pull reuqest to be created
3. Comment again and say `@AllContributorsBotDev please add jakebolam for code, doc and infra`
4. See crash

**Expected behavior**
Should return and say a branch/PR is already open.

**Screenshots**

**Additional context**
After we fix this bug, it is likely we will expose the bug branch exist, but PR is not open. We should be wary of this case too. 

sentry error of one such case: `Error: Reference already exists` 
https://sentry.io/all-contributors/github-bot/issues/844367677/?query=is%3Aunresolved

**Comment by jakebolam** [comment]
Error count on this is now 15.

@Berkmann18 I've seen one from your sandbox too.

**Comment by jakebolam** [comment]
Unfortunately I can't add any users without paying:
<img width="948" alt="screen shot 2019-01-16 at 12 47 46 pm" src="https://user-images.githubusercontent.com/3534236/51226968-01099880-198d-11e9-9cd6-a660b5906813.png">
<img width="595" alt="screen shot 2019-01-16 at 12 47 52 pm" src="https://user-images.githubusercontent.com/3534236/51226972-0535b600-198d-11e9-9284-80d3a484b77b.png">

Is there any information you need? If you're running your setup locally and using smee, you shouldn't need it

**Comment by jakebolam** [comment]
(Errors are also logged to the slack channel)

**Comment by jakebolam** [comment]
Thanks for putting this up! 🙏

**Comment by sinchang** [comment]
@jakebolam  ok, thanks a lot.
