### ISSUE TITLE
stats endpoint is timing out

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/all-contributors-bot#167]
**Describe the bug**
The stats endpoint is timing out:
https://gkioebvccg.execute-api.us-east-1.amazonaws.com/prod/probot/stats

Causing https://probot.github.io/apps/all-contributors/ to show incorrect installations.
https://raw.githubusercontent.com/probot/probot.github.io/master/_apps/all-contributors.md

From the screenshot below:
![Screen Shot 2019-03-20 at 7 55 56 PM](https://user-images.githubusercontent.com/3534236/54726600-3461d280-4b4a-11e9-92c1-bd91445e5e56.png)
We can see that the duration of the endpoint has been slowly increasing with the number of installs. Once we crossed the 30 second mark (in the last week of February) the lambda is taking longer to process than the 30second hard timeout from API Gateway, and the gateway times out.

**To Reproduce**
1. Hit end point

**Expected behavior**
Endpoint returns quickly and promptly to allow stat reporting.

**Screenshots**
![Screen Shot 2019-03-20 at 6 22 07 PM](https://user-images.githubusercontent.com/3534236/54723225-438e5380-4b3d-11e9-8745-d3789a18f269.png)

**Comment by jakebolam** [comment]
Probot has the same issue: https://github.com/probot/probot/issues/380

**Comment by jakebolam** [comment]
This PR may be us some time: https://github.com/all-contributors/all-contributors-bot/pull/133/files

**Comment by jakebolam** [comment]
@gr2m any idea how we could make the endpoint code more efficient? i.e. are there endpoints from GitHub we should be using instead

https://github.com/all-contributors/all-contributors-bot/blob/master/src/serverless-stats.js

**Comment by gr2m** [comment]
As mentioned in Slack

> I think instead of using the app to get these stats, I’d use something like Travis Cron job to get the stats on a schedule. With the latest Octokit & throttle/retry plugins, it shouldn’t be a problem in terms of hitting rate / abuse limits, but it will take a long time

I would turn off stats using the environment variable, I don’t like the endpoint to be in probot at all the way it is. GitHub should provide better APIs to get these statistics, and they are aware of the problem.

**Comment by gr2m** [comment]
[![image](https://user-images.githubusercontent.com/39992/54776944-63ba2300-4bce-11e9-87ba-3dec03b9190a.png)](https://probot.github.io/docs/configuration/)

**Comment by jakebolam** [comment]
Shipped in #175
