### ISSUE TITLE
Bot doesn't respond to issue neither create the PR

### ISSUE THREAD

**Issue by kevinwolfcr** [all-contributors/all-contributors-bot#171]
**Describe the bug**
I've mentioned the bot to add myself as the first contributor on kevinwolfcr/formal#3

**Additional context**
I don't know if I missed something, I've installed the application and allowed access to all my repos, also added the template to the README.md (https://github.com/kevinwolfcr/formal/commit/8d4c9a6005d7d7b3817f4848e2a525633b90b300), do I need to do anything else?

**Comment by jakebolam** [comment]
@kevinwolfcr just commented on your issue. Needs to be a comment on an issue or PR. Maybe we can make this clearer in the docs with a "troubleshooting" or "q&a" section

**Comment by jakebolam** [comment]
We're working on some way to do this without an issue/PR in #149

**Comment by kevinwolfcr** [comment]
Thanks, @jakebolam. Although I suggest to also watch for issue open. Example, I need to add a contributor that didn't make any pull request, or maybe just suggested ideas, it would be nice to just open an issue mentioning the bot.

**Comment by configurator** [comment]
I second @kevinwolfcr - I also just came here looking for why the newly-installed bot wasn't responding to my new issue. The only purpose of the issue was to add contributors, so it makes sense that it would respond to creating an issue, and not just to comments.

**Comment by kevinwolfcr** [comment]
@configurator a temporary workaround I made was to first create the issue explaining why I want to add someone as a collaborator and then comment mentioning the bot (kevinwolfcr/formal#5)

**Comment by ChildishGiant** [comment]
Seems this is still an issue https://github.com/cloverleaf/web/issues/444

**Comment by gr2m** [comment]
seems like it worked in the end?

**Comment by ChildishGiant** [comment]
I had to mention the person 3 times though... surely it'd make sense to check initial issue/pr bodies for commands too?

**Comment by gr2m** [comment]
The app is currently only acting on comments of issues and pull requests, not on new issues.

I agree that adding a contributor outside of an existing issue/pr thread is common, but maybe instead of creating an issue, we can provide a better way to do that. The app could provide a custom UI for that. It's just an idea right now, we are not working on it
