### ISSUE TITLE
HTML badge replacement doesn't work

### ISSUE THREAD

**Issue by kevinwolfcr** [all-contributors/all-contributors-bot#176]
**Describe the bug**
Currently the badge isn't being replaced since it is on HTML format on my README.md, I have to manually increment the number (kevinwolfcr/formal@968805004f1e45243bd58f1b32d5c7b45bc156aa)

**Additional context**
Due to JSON formatting, I had to escape the double quotes on `.all-contributorsrc` (https://github.com/kevinwolfcr/formal/blob/master/.all-contributorsrc#L35). Maybe that is broking the regex.

**Comment by jakebolam** [comment]
Thanks for reporting this @kevinwolfcr. This is an issue in the Node/CLI Api https://github.com/all-contributors/all-contributors-cli/issues/120. Once fixed there the bot will start using the latest. PRs welcome to help :)

**Comment by kevinwolfcr** [comment]
Thanks, I will watch for that issue and try to contribute :)
