### ISSUE TITLE
How can i add the `skip ci` into the commit of the bot.

### ISSUE THREAD

**Issue by kaikai1024** [all-contributors/all-contributors-bot#196]
**Is your feature request related to a problem? Please describe.**

I cannot find the info about this.

**Describe the solution you'd like**

Config the commit:

`docs: update .all-contributorsrc. [skip ci]` instead of `docs: update .all-contributorsrc`

**Describe alternatives you've considered**

None

**Additional context**

https://github.com/cryptape/cita/pull/479

**Comment by Berkmann18** [comment]
Good idea, would you like to open a PR which adds that?

**Comment by jakebolam** [comment]
@fennecdjay is working on this in https://github.com/all-contributors/all-contributors/issues/281

**Comment by fennecdjay** [comment]
@fennecdjay is working on this in all-contributors/all-contributors#281
I am! the PR is [here](https://github.com/all-contributors/all-contributors-bot/pull/216).
According to my test, it work (loook  some of my *bot* repos), but it fails the tests for now.
I must admit here I just don't known js.
@Berkmann18 and @kaikai1024, would you help me on that?
IMHO, that would be a nice addition.

**Comment by Berkmann18** [comment]
> would you help me on that?

Sure, depending on what you need help with.

**Comment by fennecdjay** [comment]
@kaikai1024 the skipCi PR #216  has been merged.
The message now end with  `[skip ci]` by default.
There is some information [here](https://github.com/fennecdjay/all-contributors/blob/ecb55dded4fe4edfac072c56383bbb1bfda3c254/docs/bot/configuration.md).

One nice and last thing to do would be testing behavior when skipCi is set to `false` (I tested it manually but it is not in the test suite (yet)).

**Comment by gr2m** [comment]
It’s not deployed to production yet, I’m waiting to get access to the staging environment

**Comment by jakebolam** [comment]
It's deployed now. @gr2m have you got access?

**Comment by gr2m** [comment]
I got the access but I forget everything you told me, past months have been very stressful, and the deployment process is quite complicated. 

I think it would be good to document the current steps it takes to deploy the app in [contributing/deployments-and-monitoring.md](https://github.com/all-contributors/all-contributors-bot/blob/master/contributing/deployments-and-monitoring.md)
