### ISSUE TITLE
Expression has no effect (CWE-480 & CWE-561)

### ISSUE THREAD

**Issue by MatheusRV** [all-contributors/all-contributors-bot#197]
An expression that has no effect and is used in a void context is most likely redundant and may indicate a bug.

In file /src/tasks/processIssueComment/OptionsConfig/index.js at line 11

this.originalOptionsSha <-This expression has no effect.

https://lgtm.com/projects/g/all-contributors/all-contributors-bot/alerts/?mode=tree&ruleFocus=7870108

**Comment by Berkmann18** [comment]
`this.originalOptionsSha` does seem to be used in `fetch()` ([line 28](https://github.com/all-contributors/all-contributors-bot/blob/master/src/tasks/processIssueComment/OptionsConfig/index.js#L28)) and has a getter ([line 83](https://github.com/all-contributors/all-contributors-bot/blob/master/src/tasks/processIssueComment/OptionsConfig/index.js#L83)).

I'm not sure if it's actually needed.
@jakebolam Any ideas?

**Comment by jakebolam** [comment]
Yeah this is needed. GitHub needs the sha of what the file contents what as, when we request an update.
