### ISSUE TITLE
Cannot Add Contributor

### ISSUE THREAD

**Issue by teamcoltra** [all-contributors/all-contributors-bot#198]
**Describe the bug**
I'm a maintainer on a project but not the owner I don't know if that makes a difference, but I write the standard "@all-contributors please add <username> for code" and it just says "We had trouble processing your request. Please try again later."

**Expected behavior**
A pull request made to add contributions

I am not sure what the specific error is because the bot isn't giving me an actionable error message.

**Comment by sinchang** [comment]
you missed contributor GitHub id.

**Comment by teamcoltra** [comment]
@sinchang sorry my bug report left it out because I just used &gt; username &lt; as a placeholder 

Well I just had a thought and deleted my .all-contributorsrc which was the following:

```
{
  "files": ["README.md","CONTRIBUTORS.md"],
  "imageSize": 100,
  "contributorsPerLine": 7,
  "badgeTemplate": "[![All Contributors](https://img.shields.io/badge/all_contributors-<%= contributors.length %>-orange.svg?style=flat-square)](#contributors)",
  "contributorTemplate": "<%= avatarBlock %><br /><%= contributions %>",
  "contributors": []
} 
```

and then it started working. This was just pulled from the example with the addition of the "CONTRIBUTORS.md" file. Not sure what in there broke it, but I would say that the bigger bug here is it not telling me what actually went wrong.

**Comment by Berkmann18** [comment]
@teamcoltra Well, normally the bot should comment when it doesn't understand a query addressed to it.

**Comment by jakebolam** [comment]
Thanks for reporting this @teamcoltra. We should totally work on surfacing our error messages better.

I believe this was caused because of https://github.com/all-contributors/all-contributors-bot/issues/201, and I've now ticketed it thanks, PRs welcome 😀 

Summary:
> The bot currently decides whether to 'init' (install the placeholders for the table and badge) for the README if there is no .all-contributorsrc file. If the file is found, it skips this step. This causes the bot to crash if a user has an .all-contributorsrc file but has nothing else.
