### ISSUE TITLE
Not updating README.md 

### ISSUE THREAD

**Issue by K-Sato1995** [all-contributors/all-contributors-bot#199]
**Describe the bug**
After running the `add` command, the bot updates the .all-contributorsrc fine. But it does not update README.md. 
Feel like I'm missing something very simple.

```
@all-contributors please add <username> for <contributions>
```
![image](https://user-images.githubusercontent.com/32632542/56729319-f29efa00-678f-11e9-924c-d1af3d5ec65f.png)

Originally I made this issue [here](https://github.com/all-contributors/all-contributors/issues/257).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by K-Sato1995** [comment]
@Berkmann18  mentioned that my `.all-contributorsrc` looks incomplete.
So I updated it like the following yet the same result.

```
{
  "files": [
    "README.md"
  ],
  "imageSize": 100,
  "contributorsPerLine": 7,
  "badgeTemplate": "[![All Contributors](https://img.shields.io/badge/all_contributors-<%= contributors.length %>-orange.svg?style=flat-square)](#contributors)",
  "contributorTemplate": "<%= avatarBlock %><br /><%= contributions %>",
  "contributors": [],
  "projectName": "name-of-the-project",
  "projectOwner": "K-Sato1995",
  "repoType": "github",
  "repoHost": "https://github.com"
}
```

**Comment by Berkmann18** [comment]
@K-Sato1995 Does that happen when you mention the bot on an issue?

**Comment by K-Sato1995** [comment]
@Berkmann18 
> Does that happen when you mention the bot on an issue?

Yes.

**Comment by Berkmann18** [comment]
Mind specifying the repo so I could have a look at it?

**Comment by K-Sato1995** [comment]
@Berkmann18 
I'm trying to figure out how to use the bot on this repo.

https://github.com/K-Sato1995/BlogPosts/blob/master/.all-contributorsrc

**Comment by jakebolam** [comment]
Thanks for reporting this @K-Sato1995 (and thanks for finding and fixing the issue @Berkmann18)

I believe this was caused because of https://github.com/all-contributors/all-contributors-bot/issues/201, and I've now ticketed it thanks, PRs welcome 😀 

Summary:
> The bot currently decides whether to 'init' (install the placeholders for the table and badge) for the README if there is no .all-contributorsrc file. If the file is found, it skips this step. This causes the bot to crash if a user has an .all-contributorsrc file but has nothing else.
