### ISSUE TITLE
add Natural Language Parsing mapping for the word  "copy"

### ISSUE THREAD

**Issue by M0nica** [all-contributors/all-contributors-bot#208]
**Is your feature request related to a problem? Please describe.**
I wanted to the all-contributors-bot to add a contributor who made content changes. I used the term "copy". 

**Describe the solution you'd like**
I was wondering if the word "copy" can be added to https://github.com/all-contributors/all-contributors-bot/blob/master/src/tasks/processIssueComment/utils/parse-comment/index.js in order to map to content or docs contribution or is the word "copy" too ambiguous to automatically map it to one or the other?

**Additional context**

<img width="817" alt="Screen Shot 2019-05-23 at 5 57 32 AM" src="https://user-images.githubusercontent.com/6998954/58243981-b4a9dd00-7d1f-11e9-911c-cb9222404645.png">

**Comment by Berkmann18** [comment]
The word "copy" indeed seems ambiguous as it could be for `docs`, `content` or even `blog`.
