### ISSUE TITLE
Does not respond to other bots' comments

### ISSUE THREAD

**Issue by mfix22** [all-contributors/all-contributors-bot#244]
Hi @jakebolam and other maintainers!

I have a question about how the All Contributors bot operates. 

Right now I am using [Ranger](https://reporanger.com) to create my All Contributor comments, as shown here: https://github.com/carbon-app/carbon/pull/858#issuecomment-531336464; however, the All Contributors bot doesn't respond. 

I assume this is because Ranger isn't an owner or something, but Ranger does have write access to this repo. 

In my opinion, Ranger should be treated almost equivalently to other maintainers, especially when they have the valid permissions. 

Really appreciate your time helping me understand this issue.

**Comment by mfix22** [comment]
Ah I see, it is because you are only listening to User requests: 

https://github.com/all-contributors/all-contributors-bot/blob/master/src/serverless-webhook.js#L83
```js
if (payload.sender.type !== 'User') {
  return {
    statusCode: 201,
    body: 'Not from a user, exiting',
  }
}
```

Is this intentional, or would you be open to extending this to `payload.sender.type !== 'Bot'`

**Comment by gr2m** [comment]
I'm not sure why it was added. Could you try to find out with `git blame`? Maybe there was a good reason?

**Comment by Berkmann18** [comment]
Yes, the bot only listens to humans and it was intentional (not sure why tho).

**Comment by mfix22** [comment]
Here is where the change was introduced: https://github.com/all-contributors/all-contributors-bot/commit/1d143321295fd25f900cc78c568b3471b2e1dfbf#diff-4dfd399fabf3b052cceb02a3d7d4750fR31

Would you be open to me adding `'Bot'` in a PR?

**Comment by mfix22** [comment]
Hey @gr2m would you be open to me adding a PR to allow @all-contributors to respond to other bots?

**Comment by gr2m** [comment]
Yes. I'm just a bit nervous deploying right now, but let's try

**Comment by mfix22** [comment]
No rush no deploying! I'll push the PR, and we can discuss there. Maybe others in the community have other qualms that I am not aware of.

**Comment by gr2m** [comment]
Thanks! Let's leave it open for a week and if there are no objections let's merge it in.
