### ISSUE TITLE
Bot not updating badge contributor count

### ISSUE THREAD

**Issue by protoEvangelion** [all-contributors/all-contributors-bot#247]
**Describe the bug**
Not sure if this is a bug or intended functionality. When I add a new contributor with the bot, it opens a PR with everything correct except for the badge count.

I have this in my config file: `"badgeTemplate": "[![All Contributors](https://img.shields.io/badge/all_contributors-<%= contributors.length %>-orange.svg?style=flat-square)](#contributors)",`

**To Reproduce**
Here is an example: 
https://github.com/node-gh/gh/pull/669/files

**Expected behavior**
Update the badge with incremented number of contributors

**Comment by ahonn** [comment]
see https://github.com/node-gh/gh/issues/676

Using a version inconsistent cli will cause the badge to not be updated. We need to upgrade the cli dependency to solve this problem.
