### ISSUE TITLE
Only have one major branch for contributor-PRs

### ISSUE THREAD

**Issue by Andre601** [all-contributors/all-contributors-bot#261]
**Is your feature request related to a problem? Please describe.**
*No issue*

**Describe the solution you'd like**
Letting the bot create one branch for each user that should be added as contributor seems a bit much in my opinion as it comes with the following (minor) issues:
- You'll have a lot of branches when adding many users. If you add 20+ users will you have 20+ branches.
- Many conflicts with other PRs can happen. When you have user A added and later add user B without merging PR for user A, will the PR with user B have conflicts when user A-PR is merged. (See #260 for related problem)

I suggest implementing a setting in the `.all-contributorsrc` file, to set a branch, in which the bot would commit changes to.
Benefits of this could be that PRs no longer won't conflict as it would be one major branch where new users just get added.
A downside would be that the bot would need to check for already open PRs to then comment on it about the newly added user.

This could also fix issues like #241, maybe https://github.com/all-contributors/all-contributors-cli/pull/196 and #260 as commiting changes wouldn't cause those (or similar) issues.

**Describe alternatives you've considered**
The only *real* alternative is the one that already exists, which is to let the bot make multiple branches (one for each user) and merge each PR... Which comes with first fixing merge-conflicts, if you created multiple PRs without merging them first.

Those are just some general thoughts and I appreciate your feedback on this.

**Comment by samajammin** [comment]
I like this approach! Seems like a clean way to solve multiple of the open issues you mentioned.

**Comment by Andre601** [comment]
Merged into one major issue (#286)
