### ISSUE TITLE
Getting into the loop of adding

### ISSUE THREAD

**Issue by skywinder** [all-contributors/all-contributors-bot#266]
**Describe the bug**
Please, check: https://github.com/skywinder/ActionSheetPicker-3.0/pull/435
I lock conversation since bot get into the loop of adding new comments.

**To Reproduce**
Look at the commetns there
looks like it started by the phrase:
"@all-contributors please add @all-contributors for docs"

**Expected behavior**
Bot have to answer once.

**Screenshots**

<img width="875" alt="image" src="https://user-images.githubusercontent.com/3356474/70030881-b3b20c00-15dc-11ea-9a9c-2b459514d7f1.png">

<img width="580" alt="image" src="https://user-images.githubusercontent.com/3356474/70030710-603fbe00-15dc-11ea-9519-3b0abacc9f65.png">

**Comment by skywinder** [comment]
looks like it started by the phrase:
"@all-contributors please add @all-contributors for docs"

<img width="875" alt="image" src="https://user-images.githubusercontent.com/3356474/70030881-b3b20c00-15dc-11ea-9a9c-2b459514d7f1.png">

**Comment by skywinder** [comment]
Whoops. Here you go there too :)
Enjoy!

**Comment by skywinder** [comment]
# Whoops. Here you go there too :) Enjoy!

**Comment by jakebolam** [comment]
@all-contributors please add @all-contributors for code, doc and infra

**Comment by jakebolam** [comment]
@all-contributors yessss mattee
