### ISSUE TITLE
Endless comment and pull request

### ISSUE THREAD

**Issue by befovy** [all-contributors/all-contributors-bot#270]
**Describe the bug**
Please see https://github.com/befovy/fijkplayer/pull/128#issuecomment-561499710

all-contributors answers comment by itself.
The first may come from a comment from commit-lint bot.
Endless comments appear soon afterwards. I have to uninstall github all-contributors bot app.

**Expected behavior**
all-contributors may should not response bot comments.

**Comment by Lrakotoson** [comment]
Same,
For my part, when it crashed, I had to disable the bot, close all pull requests and delete comments so that it would stop spamming.

**Comment by jakebolam** [comment]
Fixed in #265
