### ISSUE TITLE
Just a test

### ISSUE THREAD

**Issue by kentcdodds** [all-contributors/all-contributors-bot#28]
I just want to see this in action! This is sooooo cool!

@AllContributorBot please add kentcdodds for infrastructure

**Comment by kentcdodds** [comment]
Ah, looks like the README needs an update!

@all-contributors please add kentcdodds for infrastructure

**Comment by kentcdodds** [comment]
Oh, and the README's already updated.

Dude, this is super legit!

**Comment by jakebolam** [comment]
🎉 doesn't have full word support yet #30, and yeah only on comments (not on opening and issue or PR). BUT ITS GETTING THERE WOOO 🎉

**Comment by kentcdodds** [comment]
Dude, it's sooooo cool!

**Comment by Berkmann18** [comment]
@allcontributors Please add @ACFaul for event organizing
