### ISSUE TITLE
AllContributorsBot should be able to setup repo's initially 

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/all-contributors-bot#3]
**Is your feature request related to a problem? Please describe.**
When you type `@all-contributors please add jakebolam for code` and the repository is not setup. The bot responds and says use the CLI tool to setup the repo.

tldr: Remove project dependence on cli tool!

**Describe the solution you'd like**
It would be good if the bot could open an initial PR in these cases (or direct the user to say some other specific words for the bot to put up an init PR).
e.g.
`@AllContributorsBot setup project`
-> Puts up initial pull request for `README.md` and `.all-contributorsrc`

**Describe alternatives you've considered**
Keeping setup restricted to using the cli tool

**Additional context**

**Comment by Berkmann18** [comment]
Wouldn't having the bot set up on the user account or manually set up on a repo on Github remove the need to do any CLI setups?

Most of the bots I use are linked to my account so they are automatically "connected" to repos I make.

**Comment by jakebolam** [comment]
@Berkmann18 yes it totally would remove the need for any CLI setup!

Interesting, we could either do it when the user asks the bot, or when they install the app. 

I'm wary of doing it on install, as some orgs/users have 100's of repos and the bot would need to set them all up quickly on install. 

I think it would be good: when the bot is requested to add a user, if the repo is not setup, attempt to set it up ourselves with the requested contribution add.
