### ISSUE TITLE
When a user is found, but the bot cannot determine contributions, tell the user

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/all-contributors-bot#31]
**Is your feature request related to a problem? Please describe.**
Sometimes when asking the bot to add contributions it won't be able to determine the types of contributions, this does not stop the bot opening a PR with an empty array of contributions see https://github.com/all-contributors/all-contributors-bot/pull/29/files#diff-c47fb5a6d4fde805d2706fc934e8d354R38

**Describe the solution you'd like**
When a user is found, but the bot cannot determine contributions, tell the user. A PR should not be opened.

**Describe alternatives you've considered**

**Additional context**

**Comment by Berkmann18** [comment]
I think a found a viable solution for this.
I'll test it with my test bot (in a couple hours) but in the meantime, will submit a PR with the changes.
