### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Qeenon** [all-contributors/all-contributors-bot#318]
I've installed bot and granted permissions
https://github.com/Qeenon/mawa/issues/1

**Comment by jason-kerney** [comment]
I am having the same problem. I have installed bot, granted permissions and made a pull request, commented on the pull request, and nothing.

https://github.com/jason-kerney/StructuralEqualityAssesor

**Comment by jason-kerney** [comment]
Okay, the person I was trying to add was an organization. Evidently All Contributors does not support that.

**Comment by jason-kerney** [comment]
CLI Worked, but not able to get bot to work... :-(
