### ISSUE TITLE
First bot PR changed our table layout

### ISSUE THREAD

**Issue by jerodsanto** [all-contributors/all-contributors-bot#57]
_(Thanks so much for building this!)_

On first use with an existing contributors list (generated via the command-line tool), the bot sets `contributorsPerLine` to 7 in our config file. This is undesirable as the 7th column in each row is squished smaller than the others:

<img width="922" alt="2019-01-17 at 8 40 am" src="https://user-images.githubusercontent.com/8212/51325900-9495a480-1a33-11e9-93c3-df5116e6b769.png">

[PR here](https://github.com/thechangelog/transcripts/pull/395)

**Comment by jakebolam** [comment]
Hey @jerodsanto.

Thanks for reporting this! What should be the behaviour?

I took a look at the changelog/transcripts project README (on master) and it appears to be 7 across too. (The CLI has a default of 7, the bot explicit calls this out, you can configure this in your RC file and the bot will respect this).

To avoid confusion we could have the CLI explicitly set this setting too (for consistent behaviour)

![screenshot_20190118-091911](https://user-images.githubusercontent.com/3534236/51393654-371e5800-1b06-11e9-90ca-18f2c5cbdd1d.png)

**Comment by jerodsanto** [comment]
lol that's embarrassing I didn't even notice until I saw the bot modify the rc file! 

The behavior I'd expect is for the bot to not edit your config at all, but I'd be fine with the CLI also setting that explicitly by default.

**Comment by jakebolam** [comment]
Yes I agree modifying is a little weird, adding code to not modify in certain cases adds weird complexity to the bot (I also think being explicit in the file is a good idea). 

Do you think it would still be confusing even after? https://github.com/all-contributors/all-contributors-cli/pull/149

**Comment by jerodsanto** [comment]
I think that's Good Enough 👌

**Comment by jakebolam** [comment]
Thanks @jerodsanto. Any other issues feel free to file. Want to make this really great!
