### ISSUE TITLE
Probot is using octokit/rest 15, which is missing some features e.g. git.getRef

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/all-contributors-bot#7]
**Is your feature request related to a problem? Please describe.**
AllContributorsBot requires some features not available in the current version of `octokit/rest` in the latest version of probot (7.4.0)
`Error: Cannot read property 'getRef' of undefined") `

**Describe the solution you'd like**
We need to bump the version of the octokit/rest api in probot

**Describe alternatives you've considered**
Cloning the repo locally and using git directly (instead of via github).

**Additional context**
Looks like the probot team is on it: https://github.com/probot/probot/pull/774

**Comment by jakebolam** [comment]
Master is now running a preview version of this package, and development is unblocked 🎉

**Comment by jakebolam** [comment]
@all-contributors please add @gr2m for questions and tools.

**Comment by Berkmann18** [comment]
_Note_: The probot PR got merged and is available in `v8.0.0-beta.1`.

**Comment by gr2m** [comment]
Probot v9 is out now on latest. We accidentally published v8 & v9 ¯\\_(ツ)\_/¯

**Comment by Berkmann18** [comment]
@gr2m How?

**Comment by gr2m** [comment]
We use a pre-release version of [semantic-release](https://github.com/semantic-release/semantic-release) which supports maintenance and pre-releases. I did something wrong and semantic-release did not catch this user error and ended up creating a new major release instead of just setting the `@latest` dist-tag to point to the last release with the `@next` dist-tag

**Comment by Berkmann18** [comment]
@gr2m Ah okay.

**Comment by jakebolam** [comment]
We're now running the latest and greatest 9.0.2 https://github.com/all-contributors/all-contributors-bot/pull/170
